### ISSUE TITLE
Question: Button Code

### ISSUE THREAD

**Issue by CPad68** [eighthree/Simple-LED-Strip-Controller#4]
Hi,

I noticed in this latest version that you have removed the push button code. Are you planning on putting that back in? It was actually one of my favorite features. 

Thanks!

**Comment by eighthree** [comment]
Hi @CPad68 glad you liked the 1.x buttons! I'll look into bringing those buttons back in, listing out 50 buttons in that style with 50+ effects looked overwhelming so I made a switch to something more compact.

**Comment by CPad68** [comment]
Sorry if I was unclear. The feature I liked was the physical button that could cycle through color options without using the web interface. If you could put that in with a few options, noobs like me can customize or expand it.

Thanks! 

Chris

**Comment by eighthree** [comment]
@CPad68 Noted! Thanks for the feedback!
