### ISSUE TITLE
Wemos D1 5v powering issues

### ISSUE THREAD

**Issue by FabioEnne** [eighthree/Simple-LED-Strip-Controller#5]
The problem is that if I connect the WEMOS via USB it ALWAYS load in the right way, but if I'm powering it via the 5V pin 95% of the time it fails to correctly startup requiring to press the reset button in order to solve the problen, but sometimes it doesn't solve the problem, do you know why? I'm powering it around 4.9-5.1V is it relevant should I reduce the Voltage or rising it?

**Comment by eighthree** [comment]
@FabioEnne what's the length of your LED Strip? Do you have a cap between gnd and 5v that goes to your led strip? Whats the resistor on your data pin?

I think the issue you're having is also due to the 3v vs. 5v logic. Try using a logic level shifter like this:
https://www.adafruit.com/product/395
